# This file is a template, and might need editing before it works on your project.
# Official docker image.
image: docker:latest

services:
  - docker:dind

build:
  stage: build
  script:
    - docker login -u "gitlab-ci-token" -p "$CI_BUILD_TOKEN" $CI_REGISTRY
    - docker build -t registry.evolt.io:5005/evolt-rd/homer .
    - docker push registry.evolt.io:5005/evolt-rd/homer