# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  timeout: 5000
  host: mariadb
  username: root
  password: root

development:
  <<: *default
  database: homer_development
production:
  <<: *default
  database: homer_production

test:
  <<: *default
  database: homer_test